version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  springAPI:
    image: backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  web:
    build:
      context: ./frontend
    ports:
      - "3030:3030"


